DBNAME = "postgres"
USER = "postgres"
PASSWORD = "roaring_Lionsdb"
HOST = "datathondb.cpeue8qq0l9u.ap-southeast-1.rds.amazonaws.com"
PORT = "5432"
REGION = "ap-southeast-1"
PINECONE_API_KEY = "pcsk_5g41cA_Bc2Gq1bayboqrNBLVdd67fAKCNKLw49ENJc9QTqHU7uRag1KhqjniArXHJGZYyA"
INDEX = "datathon-2"